[project]
name = "crypto_hft"
version = "0.1.0"
description = "TECH-UB-24 Crypto HFT Project"
readme = "README.md"
requires-python = ">=3.11.0"
dependencies = [
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "websockets>=15.0.1",
]
